services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  valkey:
    image: valkey/valkey:latest
    restart: always
    env_file:
      - .env
    ports:
      - "6379:6379"
    depends_on:
      - db

  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - valkey

volumes:
  pgdata:
